#!name=彩云天气
#!desc=彩云天气

[URL Rewrite]
# 普通版广告
^https:\/\/ad\.cyapi\.cn\/v2\/req\?app_name=weather - reject-dict

[Script]
# 赏叶赏花
cytq = type=http-response, pattern=^https:\/\/wrapper\.cyapi\.cn\/v1\/activity\?app_name=weather, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/cytq.js, requires-body=true, max-size=-1, timeout=60

# 解锁vip
cytq = type=http-response, pattern=^https:\/\/biz\.cyapi\.cn\/v2\/user, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/cytq.js, requires-body=true, max-size=-1, timeout=60

# 卫星云图 48小时预报
cytq = type=http-request, pattern=^https:\/\/wrapper\.cyapi\.cn\/v1\/(satellite|nafp\/origin_images), script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/cytq.js, timeout=60

[MITM]
hostname = %APPEND% *.cyapi.cn

