#!name=咪咕音乐vip
#!desc=咪咕音乐vip

[URL Rewrite]
^https://app\.c\.nf\.migu\.cn/member/api/marketing/text - reject
^https://app\.c.nf\.migu\.cn/payment/watch-ad - reject-200

[Script]
# > 咪咕音乐vip、音质、下载
miguyinyue = type=http-response, pattern=^https?:\/\/(u|c|app).(musicapp|c.nf).migu.cn.*(user\/(queryUserInfo.do|member\/center))|(column\/(startup-pic-with-ad|marketing\/advertising)|\/resource\/skin\/list\/).*$, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/miguyinyue.js, requires-body=true, max-size=-1, timeout=60

miguyinyue = type=http-request, pattern=^https?:\/\/app.(c|pd).nf.migu.cn\/.*\/(listen-url|music\/batchQueryMusicPolicy|download-url).*$, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/miguyinyue.js, timeout=60

[MITM]
hostname = %APPEND% *.migu.cn

